apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: viewcount
spec:
  endpoints:
    - path: /actuator/prometheus
      port: http
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: viewcount
